### ISSUE TITLE
Relationship to HTTP status code usage

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/deprecation-header#17]
This was raised on the mailing list: Is there a recommended status code to use with the header field? My response to this was that there isn't one, and then @ioggstream was wondering whether we should say that. If anybody feels like that would be a good idea, please comment here. Thanks!

**Comment by ioggstream** [comment]
Thanks for filing this.

**Comment by darrelmiller** [comment]
My observation is that this header is similar in class to the "Response Context" headers https://datatracker.ietf.org/doc/html/rfc7231#section-7.4 
> The remaining response header fields provide more information about
   the target resource for potential use in later requests.

In the descriptions of these response headers there is no mention of HTTP method or Status Code unless there is some additional constraint on the use of the header for a specific scenario.  Unless there are constraints or semantic differences in this header due to the method or status code, it seems to be convention to say nothing.

**Comment by dret** [comment]
i am taking @darrelmiller's sole response as my representative sample and claim victory on this one with no changes to the draft.

**Comment by mnot** [comment]
That seems like the right outcome to me, FWIW.

**Comment by dret** [comment]
FWIW, i just "archived" this on @darrelmiller's project board because it seemed to me that having resolved issues on there is not particularly helpful, and issues don't automatically disappear from the project when they are closed.
